import { config } from "dotenv";
config();

import { prisma } from "../src/lib/db";
import { parseAISystemMutationInput } from "../src/lib/ai-system-write";
import type { AISystemFormData } from "../src/lib/schema";

const seeds = [
  {
    systemName: "ChatGPT Enterprise - Internal Drafting",
    shortDescription: "Used by employees to draft internal reports, emails, meeting summaries, and policy documents.",
    businessFunction: "IT / Engineering",
    businessOwner: "IT Department",
    technicalOwner: "IT Department",
    status: "Production",
    countriesUsed: ["United Kingdom", "Germany"],
    outputsUsedInEu: "Yes",
    users: ["Employees"],
    affectedPersons: ["No identifiable individuals"],
    deploymentContext: "Employee-facing",
    outputTypes: ["Text content", "Summary"],
    affectsDecisionsAboutPeople: "No",
    humanReviewOrOverride: "Yes",
    impactIfWrong: "Low impact",
    systemTypes: ["Generative AI", "General-purpose AI / foundation model"],
    decisionLogicType: "General-purpose AI / LLM",
    learnedParametersUsedInProduction: "Yes",
    underlyingModelOrTool: "GPT-4o",
    modelProvider: "OpenAI",
    usesGpaiOrLlm: "Yes",
    usesRag: "No",
    canCallToolsOrApis: "No",
    canTakeActions: "No",
    generatesContent: "Yes",
    interactsDirectlyWithPeople: "Yes",
    usesPersonalData: "No",
    usesSensitiveData: "No",
    profilesIndividuals: "No",
    dataTypes: ["Internal documents"],
    buildType: "Bought/licensed from vendor",
    vendorName: "Microsoft",
    vendorCountry: "United States",
    modelProviderName: "OpenAI",
    modelProviderCountry: "United States",
    brandedUnderOrganisationName: "No",
    vendorBrandVisible: "Yes",
    modifiedFineTunedRebrandedOrRepurposed: "No",
    riskDomainFlags: ["Internal productivity only"],
  },
  {
    systemName: "Customer Support Chatbot",
    shortDescription: "AI-powered chatbot that handles first-line customer queries on the website, including FAQs, order tracking, and complaint triage.",
    businessFunction: "Customer Service",
    businessOwner: "Customer Service Director",
    technicalOwner: "Product Engineering",
    status: "Production",
    countriesUsed: ["United Kingdom", "Ireland", "France"],
    outputsUsedInEu: "Yes",
    users: ["Customers", "Public users"],
    affectedPersons: ["Customers"],
    deploymentContext: "Customer-facing",
    outputTypes: ["Text content", "Recommendation"],
    affectsDecisionsAboutPeople: "No",
    humanReviewOrOverride: "Yes",
    impactIfWrong: "Medium impact",
    systemTypes: ["Chatbot", "Generative AI", "RAG system"],
    decisionLogicType: "General-purpose AI / LLM",
    learnedParametersUsedInProduction: "Yes",
    underlyingModelOrTool: "Claude 3.5 Sonnet",
    modelProvider: "Anthropic",
    usesGpaiOrLlm: "Yes",
    usesRag: "Yes",
    canCallToolsOrApis: "Yes",
    canTakeActions: "No",
    generatesContent: "Yes",
    interactsDirectlyWithPeople: "Yes",
    usesPersonalData: "Yes",
    usesSensitiveData: "No",
    profilesIndividuals: "No",
    dataTypes: ["Customer data", "Transaction data"],
    buildType: "Hybrid: internal plus vendor",
    vendorName: "Intercom",
    vendorCountry: "United States",
    modelProviderName: "Anthropic",
    modelProviderCountry: "United States",
    brandedUnderOrganisationName: "Yes",
    vendorBrandVisible: "No",
    modifiedFineTunedRebrandedOrRepurposed: "Yes",
    riskDomainFlags: ["Customer service or customer interaction"],
  },
  {
    systemName: "Vendor CV Screening Tool",
    shortDescription: "Third-party tool that scores and ranks job applicants based on their CVs before shortlisting for human review.",
    businessFunction: "HR",
    businessOwner: "Head of Talent Acquisition",
    technicalOwner: "HR Systems Team",
    status: "Production",
    countriesUsed: ["United Kingdom"],
    outputsUsedInEu: "No",
    users: ["Employees"],
    affectedPersons: ["Job applicants"],
    deploymentContext: "Internal only",
    outputTypes: ["Score", "Ranking", "Classification"],
    affectsDecisionsAboutPeople: "Yes",
    humanReviewOrOverride: "Yes",
    impactIfWrong: "High impact",
    systemTypes: ["Machine learning model", "Recommender system"],
    decisionLogicType: "Machine learning model trained on data",
    learnedParametersUsedInProduction: "Yes",
    underlyingModelOrTool: "Proprietary ML model",
    modelProvider: "HireVue",
    usesGpaiOrLlm: "No",
    usesRag: "No",
    canCallToolsOrApis: "No",
    canTakeActions: "No",
    generatesContent: "No",
    interactsDirectlyWithPeople: "No",
    usesPersonalData: "Yes",
    usesSensitiveData: "Not sure",
    profilesIndividuals: "Yes",
    dataTypes: ["Candidate / applicant data", "Behavioural data"],
    buildType: "Bought/licensed from vendor",
    vendorName: "HireVue",
    vendorCountry: "United States",
    brandedUnderOrganisationName: "No",
    vendorBrandVisible: "Yes",
    modifiedFineTunedRebrandedOrRepurposed: "No",
    riskDomainFlags: ["Recruitment or hiring"],
  },
  {
    systemName: "Internal Credit Scoring Model",
    shortDescription: "In-house logistic regression model that calculates a credit score for personal loan applicants and triggers automatic decline below a threshold.",
    businessFunction: "Risk",
    businessOwner: "Chief Risk Officer",
    technicalOwner: "Data Science Team",
    status: "Production",
    countriesUsed: ["United Kingdom", "Ireland"],
    outputsUsedInEu: "Yes",
    users: ["Other systems / automated processes"],
    affectedPersons: ["Borrowers / applicants for credit", "Customers"],
    deploymentContext: "Used by other systems",
    outputTypes: ["Score", "Decision"],
    affectsDecisionsAboutPeople: "Yes",
    humanReviewOrOverride: "Yes",
    impactIfWrong: "High impact",
    systemTypes: ["Statistical model", "Machine learning model"],
    decisionLogicType: "Statistical model with estimated coefficients",
    learnedParametersUsedInProduction: "Yes",
    underlyingModelOrTool: "Logistic regression (scikit-learn)",
    modelProvider: "Internal",
    usesGpaiOrLlm: "No",
    usesRag: "No",
    canCallToolsOrApis: "Yes",
    canTakeActions: "Yes",
    generatesContent: "No",
    interactsDirectlyWithPeople: "No",
    usesPersonalData: "Yes",
    usesSensitiveData: "No",
    profilesIndividuals: "Yes",
    dataTypes: ["Customer data", "Financial data", "Transaction data", "Behavioural data"],
    buildType: "Built internally",
    brandedUnderOrganisationName: "Yes",
    vendorBrandVisible: "No",
    modifiedFineTunedRebrandedOrRepurposed: "No",
    riskDomainFlags: ["Creditworthiness, lending, credit scoring, or loan approval"],
  },
  {
    systemName: "Internal Policy RAG Assistant",
    shortDescription: "Internal chatbot that lets employees search and ask questions about HR policies, compliance procedures, and regulatory guidance documents.",
    businessFunction: "Compliance",
    businessOwner: "Head of Compliance",
    technicalOwner: "IT / Engineering",
    status: "Pilot",
    countriesUsed: ["United Kingdom"],
    outputsUsedInEu: "No",
    users: ["Employees"],
    affectedPersons: ["No identifiable individuals"],
    deploymentContext: "Employee-facing",
    outputTypes: ["Text content", "Summary", "Recommendation"],
    affectsDecisionsAboutPeople: "No",
    humanReviewOrOverride: "Yes",
    impactIfWrong: "Medium impact",
    systemTypes: ["RAG system", "Chatbot", "Generative AI"],
    decisionLogicType: "General-purpose AI / LLM",
    learnedParametersUsedInProduction: "Yes",
    underlyingModelOrTool: "GPT-4o mini",
    modelProvider: "OpenAI",
    usesGpaiOrLlm: "Yes",
    usesRag: "Yes",
    canCallToolsOrApis: "No",
    canTakeActions: "No",
    generatesContent: "Yes",
    interactsDirectlyWithPeople: "Yes",
    usesPersonalData: "No",
    usesSensitiveData: "No",
    profilesIndividuals: "No",
    dataTypes: ["Internal documents"],
    buildType: "Built internally",
    brandedUnderOrganisationName: "Yes",
    vendorBrandVisible: "No",
    modifiedFineTunedRebrandedOrRepurposed: "No",
    riskDomainFlags: ["Internal productivity only", "Compliance or regulatory support"],
  },
] satisfies AISystemFormData[];

function seedId(systemName: string): string {
  return `seed-${systemName.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")}`;
}

async function main() {
  console.log("Seeding database...");
  for (const seed of seeds) {
    const { mutationData } = parseAISystemMutationInput(seed);
    const id = seedId(seed.systemName);

    await prisma.aISystem.upsert({
      where: { id },
      update: mutationData,
      create: { id, ...mutationData },
    });
  }
  console.log(`Done. ${seeds.length} systems seeded.`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
