-- CreateTable
CREATE TABLE "AISystem" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "systemName" TEXT NOT NULL,
    "shortDescription" TEXT NOT NULL,
    "businessFunction" TEXT,
    "businessOwner" TEXT,
    "technicalOwner" TEXT,
    "status" TEXT,
    "countriesUsed" TEXT,
    "outputsUsedInEu" TEXT,
    "users" TEXT,
    "affectedPersons" TEXT,
    "deploymentContext" TEXT,
    "outputTypes" TEXT,
    "affectsDecisionsAboutPeople" TEXT,
    "humanReviewOrOverride" TEXT,
    "impactIfWrong" TEXT,
    "useCaseNotes" TEXT,
    "systemTypes" TEXT,
    "decisionLogicType" TEXT,
    "learnedParametersUsedInProduction" TEXT,
    "underlyingModelOrTool" TEXT,
    "modelProvider" TEXT,
    "usesGpaiOrLlm" TEXT,
    "usesRag" TEXT,
    "canCallToolsOrApis" TEXT,
    "canTakeActions" TEXT,
    "generatesContent" TEXT,
    "interactsDirectlyWithPeople" TEXT,
    "usesPersonalData" TEXT,
    "usesSensitiveData" TEXT,
    "profilesIndividuals" TEXT,
    "dataTypes" TEXT,
    "dataNotes" TEXT,
    "buildType" TEXT,
    "vendorName" TEXT,
    "vendorCountry" TEXT,
    "modelProviderName" TEXT,
    "modelProviderCountry" TEXT,
    "brandedUnderOrganisationName" TEXT,
    "vendorBrandVisible" TEXT,
    "modifiedFineTunedRebrandedOrRepurposed" TEXT,
    "supplyChainNotes" TEXT,
    "riskDomainFlags" TEXT,
    "completenessScore" INTEGER
);
